---
# Source: default-module/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-logger
  labels:
    
    helm.sh/chart: default-module-1.16.2
    
    app.kubernetes.io/name: "busy-logger"
    app.kubernetes.io/instance: "busy-logger"
    app.kubernetes.io/managed-by: "Helm"
spec:
  # DeploymentSpec.paused - Ignored because no way of unsetting it
  # DeploymentSepc.revisionHistoryLimit - Ignored because empty and 0 are different
  selector:
    matchLabels:
      
      app.kubernetes.io/name: "busy-logger"
      app.kubernetes.io/instance: "busy-logger"
  template:
    metadata:
      labels:
        
        app.kubernetes.io/name: "busy-logger"
        app.kubernetes.io/instance: "busy-logger"
      annotations:
        checksum/config: 1e1f7bc693b2808974552e3dfdcd12eaeb86e6fdb2a606cb4bb1b46b6c92074b
    spec:
      # PodSpec.activeDeadlineSeconds - Ignored because it only really applies to Jobs
      # PodSpec.dnsConfig - Ignored
      # PodSpec.dnsPolicy - Ignored
      # PodSpec.enableServiceLinks - Ignored because is set to true by default
      # PodSpec.initContainers - Ignored for now because we need to solve the ordering problem first
      # PosSprec.os - Ignored because this is an alpha field and requires the IdentifyPodOS feature
      # PodSpec.serviceAccount - Ignored because it is officially deprecated
      containers:
        - name: busybox-logger
          image: "registry.humanitec.io/qa-public/busybox-logger:1.1.0"
          resources:
            limits:
              cpu: "0.250"
              memory: 256Mi
            requests:
              cpu: "0.025"
              memory: 64Mi
          envFrom:
          - configMapRef:
              name: busy-logger-configmap-busybox-logger
      imagePullSecrets:
          []
    # Volumes part
