---
# Source: default-module/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: busy-logger
  labels:
    
    helm.sh/chart: default-module-1.16.2
    
    app.kubernetes.io/name: "busy-logger"
    app.kubernetes.io/instance: "busy-logger"
    app.kubernetes.io/managed-by: "Helm"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: port-default
  selector:
    
    app.kubernetes.io/name: "busy-logger"
    app.kubernetes.io/instance: "busy-logger"
