apiVersion: humanitec.io/v1alpha1
kind: WorkloadTemplate
metadata:
  annotations:
    app.humanitec.io/deployment: 1758e9a0958d47a7
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: operator-test-deploy
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: nils-org2
  name: workloadtemplate-busybox
spec:
  manifests:
  - apiVersion: v1
    data:
      someenvvar: test
    kind: ConfigMap
    metadata:
      labels:
        app.kubernetes.io/instance: busybox
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: busybox
        helm.sh/chart: default-module-1.16.1
      name: busybox-configmap-busybox-logger
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/instance: busybox
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: busybox
        helm.sh/chart: default-module-1.16.1
      name: busybox
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: busybox
          app.kubernetes.io/name: busybox
      template:
        metadata:
          annotations:
            checksum/config: ccf704bbc1258f79480de673b53421373ff779e84667c832a915d0919ab0f21f
          labels:
            app.kubernetes.io/instance: busybox
            app.kubernetes.io/name: busybox
        spec:
          containers:
          - envFrom:
            - configMapRef:
                name: busybox-configmap-busybox-logger
            image: registry.humanitec.io/qa-public/busybox-logger:1.1.0
            name: busybox-logger
            resources:
              limits:
                cpu: "0.250"
                memory: 256Mi
              requests:
                cpu: "0.025"
                memory: 64Mi
          imagePullSecrets: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/instance: busybox
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: busybox
        helm.sh/chart: default-module-1.16.1
      name: busybox
    spec:
      ports:
      - name: port-default
        port: 8080
        protocol: TCP
      selector:
        app.kubernetes.io/instance: busybox
        app.kubernetes.io/name: busybox
      type: ClusterIP
