apiVersion: humanitec.io/v1alpha1
kind: Application
metadata:
  annotations:
    app.humanitec.io/deployment: 17598800370b064c
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: operator-test-deploy
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: nils-org2
  name: application-operator-test-deploy
spec:
  workloads:
  - condition:
      success: deploy
      when: deploy
    dependsOnResources:
    - resource-59ffd31db38da2025149471c090da1fc67a3ac3a
    name: busybox
    templateName: workloadtemplate-busybox
status: {}
