apiVersion: humanitec.io/v1alpha1
kind: Resource
metadata:
  annotations:
    app.humanitec.io/definition-id: default-humanitec-workload-res
    app.humanitec.io/deployment: 17598800370b064c
    app.humanitec.io/matching-criteria-id: 68dabd122d4a7d42
  creationTimestamp: null
  labels:
    app.humanitec.io/app-id: operator-test-deploy
    app.humanitec.io/env-id: development
    app.humanitec.io/org-id: nils-org2
  name: resource-59ffd31db38da2025149471c090da1fc67a3ac3a
spec:
  configMapName: resource-configmap-59ffd31db38da2025149471c090da1fc67a3ac3a
  dependsOn: []
  driver: builtin://template
  driverInputs:
    driver:
      secrets: {}
      values: {}
    resource:
      id: busybox
      profile: humanitec/default-module
      spec:
        containers:
          busybox-logger:
            files: {}
            image: registry.humanitec.io/qa-public/busybox-logger:1.1.0
            resources:
              limits:
                cpu: "0.250"
                memory: 256Mi
              requests:
                cpu: "0.025"
                memory: 64Mi
            variables:
              someenvvar: test
            volume_mounts: {}
  driverType: humanitec/template
  guresid: 59ffd31db38da2025149471c090da1fc67a3ac3a
  id: modules.busybox
  secretName: resource-secret-59ffd31db38da2025149471c090da1fc67a3ac3a
  secretStoreConfigRef:
    name: test-vault-instance
    namespace: ""
  type: workload
  workloadPatchName: resource-patch-59ffd31db38da2025149471c090da1fc67a3ac3a
status: {}
